#cloud-config
package_update: true
package_upgrade: true

packages:
  - vim
  - bash-completion

users:
  - name: cca-user
    lock_passwd: true
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: docker
    lock_passwd: true
    ssh_authorized_keys:
      - "${public_key}"

runcmd:
  - curl -fsSL https://get.docker.com -o get-docker.sh; sudo sh get-docker.sh
  - sudo systemctl start docker.service
  - sudo systemctl enable docker.service
