#cloud-config

package_update: true
package_upgrade: true

packages:
  - vim
  - bash-completion

users:
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: docker
    lock_passwd: true
    ssh_authorized_keys:
      - "${public_key}"
