#cloud-config

write_files:
  -   content: cloud-init lock for updates.
      path: /tmp/cloud_init.lock  

package_update: true
package_upgrade: true

packages:
  - vim
  - bash-completion
  - parted

users:
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: docker
    lock_passwd: true
    ssh_authorized_keys:
      - "${public_key}"

runcmd: 
    - [ rm, /tmp/cloud_init.lock ]